# Site settings
title: Firefly
description: A broswer-based interactive particle visualization app

url: https://alexbgurvi.ch/Firefly/website/_site  # the base hostname and protocol for your site, e.g. http://example.com
domain: alexbgurvi.ch/Firefly/website/_site       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
baseurl: "/Firefly/website/_site" # the subpath of your site, e.g. /blog

# User settings
username: Firefly
user_title: a browser-based interactive particle visualization app
email: agurvich@u.northwestern.edu
#twitter_username: lorem_ipsum
github_username:  agurvich/Firefly
#gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
  #id: ""

exclude: ['package.json', 'src' , 'node_modules']
